[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
namenode_ip=10.10.0.4
datanodes_ips=10.10.0.3,10.10.0.2

[master]
master-node ansible_host=34.52.212.217 ansible_user=newsletters_box149_gmail_com ansible_ssh_private_key_file=/Users/jules/.ssh/google_compute_engine

[edge]
edge-node ansible_host=34.77.65.246 ansible_user=newsletters_box149_gmail_com ansible_ssh_private_key_file=/Users/jules/.ssh/google_compute_engine

[workers]

worker-1-node ansible_host=10.10.0.3 ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i /Users/jules/.ssh/google_compute_engine newsletters_box149_gmail_com@34.77.65.246"' ansible_user=newsletters_box149_gmail_com ansible_ssh_private_key_file=/Users/jules/.ssh/google_compute_engine

worker-2-node ansible_host=10.10.0.2 ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i /Users/jules/.ssh/google_compute_engine newsletters_box149_gmail_com@34.77.65.246"' ansible_user=newsletters_box149_gmail_com ansible_ssh_private_key_file=/Users/jules/.ssh/google_compute_engine

