[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
namenode_ip=10.10.0.4
datanodes_ips=10.10.0.2,10.10.0.5

[master]
master-node ansible_host=35.195.241.125 ansible_user=terraform-user ansible_ssh_private_key_file=/Users/jules/.ssh/gcp_vm_key_nopass

[edge]
edge-node ansible_host=34.79.87.178 ansible_user=terraform-user ansible_ssh_private_key_file=/Users/jules/.ssh/gcp_vm_key_nopass

[workers]

worker-1-node ansible_host=104.199.33.183 ansible_user=terraform-user ansible_ssh_private_key_file=/Users/jules/.ssh/gcp_vm_key_nopass

worker-2-node ansible_host=10.10.0.5 ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i /Users/jules/.ssh/gcp_vm_key_nopass terraform-user@35.195.241.125"' ansible_user=terraform-user ansible_ssh_private_key_file=/Users/jules/.ssh/gcp_vm_key_nopass

