[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
namenode_ip=34.78.131.236
datanodes_ips=10.10.0.4,10.10.0.5

[master]
master-node ansible_host=34.78.131.236 ansible_user=terraform-user ansible_ssh_private_key_file=/Users/jules/.ssh/gcp_vm_key_nopass

[edge]
edge-node ansible_host=35.240.36.143 ansible_user=terraform-user ansible_ssh_private_key_file=/Users/jules/.ssh/gcp_vm_key_nopass

[workers]

worker-1-node ansible_host=34.77.148.49 ansible_user=terraform-user ansible_ssh_private_key_file=/Users/jules/.ssh/gcp_vm_key_nopass

worker-2-node ansible_host=10.10.0.5 ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i /Users/jules/.ssh/gcp_vm_key_nopass terraform-user@34.78.131.236"' ansible_user=terraform-user ansible_ssh_private_key_file=/Users/jules/.ssh/gcp_vm_key_nopass

