---
- name: Installer JDK 8u202
  hosts: master
  become: yes
  vars:
    java_url: "https://hagimont.freeboxos.fr/hagimont/software/jdk-8u202-linux-x64.tar.gz"
    install_base_dir: "/opt/java"
    java_folder_name: "jdk1.8.0_202"
    java_home: "{{ install_base_dir }}/{{ java_folder_name }}"
    # On définit explicitement l'utilisateur pour le chemin
    target_user: "terraform-user"

  tasks:
    - name: Créer le répertoire d'installation
      file:
        path: "{{ install_base_dir }}"
        state: directory
        mode: '0755'

    - name: Télécharger et extraire le JDK
      unarchive:
        src: "{{ java_url }}"
        dest: "{{ install_base_dir }}"
        remote_src: yes
        creates: "{{ java_home }}"

    - name: Configurer JAVA_HOME et PATH dans le .bashrc
      blockinfile:
        path: "/home/{{ target_user }}/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: JAVA 8"
        block: |
          export JAVA_HOME={{ java_home }}
          export PATH=$JAVA_HOME/bin:$PATH
        create: yes
        mode: '0644'
        owner: "{{ target_user }}"