---
- name: Créer le répertoire d'installation Spark
  file:
    path: "{{ install_base_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ target_user }}"
    group: "{{ target_user }}"

- name: Télécharger et extraire Hadoop depuis Google Cloud Storage
  unarchive:
    src: "{{ spark_url }}"
    dest: "{{ install_base_dir }}"
    remote_src: yes
    creates: "{{ hadoop_home }}"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"

- name: Création manuelle du dossier logs Spark avec les bons droits
  file:
    path: "/opt/spark/spark-2.4.3-bin-hadoop2.7/logs"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0775'

- name: Corriger les permissions pour le répertoire de travail Spark
  ansible.builtin.file:
    path: "/opt/spark/spark-2.4.3-bin-hadoop2.7"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    recurse: yes
    state: directory
  become: yes

- name: Configurer SPARK_HOME et PATH dans le .bashrc
  blockinfile:
    path: "/home/{{ target_user }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: SPARK"
    block: |
      export SPARK_HOME={{ spark_home }}
      export PATH=$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin
    create: yes
    mode: '0644'
    owner: "{{ target_user }}"
    group: "{{ target_user }}"

- name: Déployer slaves sur le NameNode
  template:
    src: slaves
    dest: "{{ spark_home }}/conf/slaves"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"

- name: Déployer spark-env.sh sur le DataNode et les DataNodes
  template:
    src: spark-env.sh
    dest: "{{ spark_home }}/conf/spark-env.sh"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"

