[master]
master-node ansible_host=34.78.117.250

[workers]
worker-node ansible_host=34.34.143.71

[edge]
edge-node ansible_host=104.199.98.145

[all:vars]
ansible_user=terraform-user
ansible_ssh_private_key_file=/Users/jules/.ssh/gcp_vm_key_nopass
