---
- name: S'assurer que le répertoire .ssh existe
  file:
    path: "/home/{{ target_user }}/.ssh" 
    state: directory
    mode: '0700'
    owner: "{{ target_user }}"
    group: "{{ target_user }}"

- name: Déployer la clé ssh (Clé Privée) sur le Master/Namenode
  copy:
    src: "gcp_vm_key_nopass" 
    dest: "/home/{{ target_user }}/.ssh/gcp_vm_key_nopass" 
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0600' 

- name: Déployer la clé ssh (Clé Publique) sur le Master/Namenode
  copy:
    src: "gcp_vm_key_nopass.pub" 
    dest: "/home/{{ target_user }}/.ssh/gcp_vm_key_nopass.pub" 
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0600' 

- name: Configurer le fichier SSH config pour l'utilisateur
  blockinfile:
    path: "/home/{{ target_user }}/.ssh/config"
    create: yes
    mode: '0600'
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    block: |
      Host 10.10.0.*
          IdentityFile ~/.ssh/gcp_vm_key_nopass
          User {{ target_user }}
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null

- name: "S'assurer que l'utilisateur peut se connecter à lui-même"
  shell: |
    cat /home/{{ target_user }}/.ssh/gcp_vm_key_nopass.pub >> /home/{{ target_user }}/.ssh/authorized_keys
    chown {{ target_user }}:{{ target_user }} /home/{{ target_user }}/.ssh/authorized_keys
    chmod 600 /home/{{ target_user }}/.ssh/authorized_keys
  args:
    creates: "/home/{{ target_user }}/.ssh/authorized_keys_done"

- name: "Désactiver la vérification stricte des clés SSH (évite le yes/no)"
  copy:
    dest: "/home/{{ target_user }}/.ssh/config"
    content: |
      Host *
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null
          IdentityFile /home/{{ target_user }}/.ssh/gcp_vm_key_nopass
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0600'
