---
- name: Ajout d'un user admin dans le groupe admin_edge_front
  hosts: edge
  become: yes
  vars:  
    admin_user: josua_jerrynithiyendra02_gmail_c
  tasks:
    - name: Ajouter l'utilisateur au groupe
      user:
        name: "{{ admin_user }}"
        groups: admin_edge_front
        append: yes

- name: Installation de la Big Data Stack (Edge)
  hosts: edge
  become: yes
  roles:
    - java
    - hadoop
    - spark
    - wordcount
