[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_ssh_private_key_file=/home/joshuajn02/.ssh/admin
ansible_user="josua_jerrynithiyendra02_gmail_c"
namenode_ip=10.10.10.5
datanodes_ips=10.10.10.3,10.10.10.4,10.10.10.6,10.10.10.8,10.10.10.2,10.10.10.7


[master]
master-hdfs-spark ansible_host=34.170.98.55  

[workers]
worker-1 ansible_host=10.10.10.3
worker-2 ansible_host=10.10.10.4
worker-3 ansible_host=10.10.10.6
worker-4 ansible_host=10.10.10.8
worker-5 ansible_host=10.10.10.2
worker-6 ansible_host=10.10.10.7


[workers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -o StrictHostKeyChecking=no -W %h:%p -i /home/joshuajn02/.ssh/admin josua_jerrynithiyendra02_gmail_c@34.170.98.55"'



[edge]
edge ansible_host=34.57.216.128  


[edge:vars]
edge_ip=192.168.20.2


