[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_ssh_private_key_file=/home/joshuajn02/.ssh/admin
ansible_user="josua_jerrynithiyendra02_gmail_c"
namenode_ip=10.10.10.2
datanodes_ips=10.10.10.8,10.10.10.14,10.10.10.7,10.10.10.10,10.10.10.6,10.10.10.5,10.10.10.9,10.10.10.3,10.10.10.4,10.10.10.12,10.10.10.13,10.10.10.11


[master]
master-hdfs-spark ansible_host=35.239.30.184  

[workers]
worker-1 ansible_host=10.10.10.8
worker-2 ansible_host=10.10.10.14
worker-3 ansible_host=10.10.10.7
worker-4 ansible_host=10.10.10.10
worker-5 ansible_host=10.10.10.6
worker-6 ansible_host=10.10.10.5
worker-7 ansible_host=10.10.10.9
worker-8 ansible_host=10.10.10.3
worker-9 ansible_host=10.10.10.4
worker-10 ansible_host=10.10.10.12
worker-11 ansible_host=10.10.10.13
worker-12 ansible_host=10.10.10.11


[workers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -o StrictHostKeyChecking=no -W %h:%p -i /home/joshuajn02/.ssh/admin josua_jerrynithiyendra02_gmail_c@35.239.30.184"'



[edge]
edge ansible_host=136.116.182.203  


[edge:vars]
edge_ip=192.168.20.2


