---
target_user: "newsletters_box149_gmail_com"
install_base_dir: "/home/{{target_user}}/.ssh"
ssh_file_name: "key_master_worker"
ssh_key_path: "{{install_base_dir}}/{{ssh_file_name}}"
gcp_project_id: "projet-infrastructure"