---
wordcount_url: "https://hagimont.freeboxos.fr/hagimont/resources-N7/bigdata/scale-subject.tgz"
target_user: "terraform-user"
install_base_dir: "/home/{{target_user}}/wordcount"
wordcount_folder_name: "scale-subject"
wordcount_home: "{{ install_base_dir }}/{{ wordcount_folder_name }}"