[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_ssh_private_key_file=/home/joshuajn02/.ssh/admin.pub
ansible_user=admin
namenode_ip=10.10.10.12
datanodes_ips=10.10.10.14,10.10.10.10,10.10.10.11,10.10.10.8,10.10.10.13,10.10.10.9


[master]
master-hdfs-spark ansible_host=35.188.195.92  

[workers]
worker-1 ansible_host=10.10.10.14
worker-2 ansible_host=10.10.10.10
worker-3 ansible_host=10.10.10.11
worker-4 ansible_host=10.10.10.8
worker-5 ansible_host=10.10.10.13
worker-6 ansible_host=10.10.10.9


[workers:vars]
ansible_ssh_common_args='-J admin@35.188.195.92'


